host: "localhost"
port: 8181

database_url: ""

db_host: "localhost"
db_port: 5432
db_user: "myuser"
db_password: "mypassword"
db_name: "mydatabase"
db_sslmode: "disable"

test_db_name: "test_mydatabase"
